services:
  openhab:
    container_name: "openhab"
    image: "openhab/openhab"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/opt/openhab/conf:/openhab/conf"
      - "/opt/openhab/userdata:/openhab/userdata"
      - "/opt/openhab/addons:/openhab/addons"
    environment:
      CRYPTO_POLICY: "unlimited"
      USER_ID: 998
      GROUP_ID: 997
    restart: "unless-stopped"
    network_mode: "host"

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - "/opt/mosquitto/config:/mosquitto/config"
      - "/opt/mosquitto/data:/mosquitto/data"
      - "/opt/mosquitto/log:/mosquitto/log"
    ports:
      - 1884:1883
      - 9002:9001
    restart: "unless-stopped"

